[package]
name = "nativelink-bep"
version = "0.3.0"
edition = "2021"

[dependencies]
nativelink-error = { path = "../nativelink-error" }

arc-cell = "0.3.3"
bazel-bep = { version = "0.2.2", features = ["server"] }
futures = "0.3.30"
tonic = { version = "0.10.2", features = ["gzip", "tls"] }
tokio = { version = "1.37.0", features = ["sync", "rt"] }
tokio-stream = { version = "0.1.15", features = ["sync"] }
tracing = "0.1.40"
redis = { version = "0.25.2", features = ["tokio-comp", "tokio-rustls-comp", "connection-manager"] }
