---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nativelink-worker-lre-java
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nativelink-worker-lre-java
  template:
    metadata:
      labels:
        app: nativelink-worker-lre-java
    spec:
      initContainers:
      - name: setup-entrypoint
        image: nixpkgs/nix-flakes:latest
        command: ["/bin/sh", "-c"]
        # The kind setup mounts the nativelink repository into the kind nodes at
        # `/mnt/src_root`. This ensures that the tags between the worker configs
        # and bazel toolchains match when this setup is run in CI.
        #
        # WARNING: The platform is *not* necessarily the container that is
        # actually deployed here. The generator container in this example was
        # `rbe-autogen-lre-java:<sometag>` and the platform was modified
        # after the fact to be `lre-java:<sometag>`. The deployed container
        # we use as worker is
        # `nativelink-worker-lre-java:<some_potentially_other_tag>` which is a
        # completely separate extension of the `lre-java` base image.
        args:
          - |
            NATIVELINK_WORKER_PLATFORM=docker://lre-java:$(nix eval /mnt/src_root#lre-java.imageTag --raw) &&
            printf '#!/bin/sh\nexport NATIVELINK_WORKER_PLATFORM=%s\nexec "$@"' "$NATIVELINK_WORKER_PLATFORM" > /entrypoint/entrypoint.sh &&
            chmod +x /entrypoint/entrypoint.sh
        volumeMounts:
          - name: entrypoint
            mountPath: /entrypoint
          - name: mnt
            mountPath: /mnt
      containers:
        - name: nativelink-worker-lre-java
          # This image will be edited by kustomize
          image: nativelink-worker-lre-java
          env:
            - name: RUST_LOG
              value: warn
            - name: CAS_ENDPOINT
              value: nativelink-cas
            - name: SCHEDULER_ENDPOINT
              value: nativelink-scheduler
          volumeMounts:
            - name: worker-config
              mountPath: /worker.json
              subPath: worker.json
            - name: entrypoint
              mountPath: /entrypoint
          command: ["/entrypoint/entrypoint.sh"]
          args: ["/bin/nativelink", "/worker.json"]
      volumes:
        - name: entrypoint
          emptyDir: {}
        - name: worker-config
          configMap:
            name: worker
        - name: mnt
          hostPath:
            path: /mnt
