---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nativelink-worker-chromium
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nativelink-worker-chromium
  template:
    metadata:
      labels:
        app: nativelink-worker-chromium
    spec:
      containers:
        - name: nativelink-worker-chromium
          # This image will be edited by kustomize.
          image: nativelink-worker-chromium
          env:
            - name: RUST_LOG
              value: info
            - name: CAS_ENDPOINT
              value: nativelink-cas
            - name: SCHEDULER_ENDPOINT
              value: nativelink-scheduler
          volumeMounts:
            - name: worker-config
              mountPath: /worker.json
              subPath: worker.json
          command: ["/bin/nativelink"]
          args: ["/worker.json"]
      volumes:
        - name: worker-config
          configMap:
            name: worker
