---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - cas.yaml
  - scheduler.yaml
  - routes.yaml

configMapGenerator:
  - name: cas
    files:
      - cas.json
  - name: scheduler
    files:
      - scheduler.json
  - name: worker
    files:
      - worker.json

images:
  - name: nativelink

secretGenerator:
  - name: tls-secret
    files:
      - example-do-not-use-in-prod-rootca.crt
      - example-do-not-use-in-prod-key.pem
