---
apiVersion: gateway.networking.k8s.io/v1alpha2
kind: GRPCRoute
metadata:
  name: cache-route
spec:
  parentRefs:
    - name: cache
      sectionName: cache
  rules:
    - backendRefs:
        - name: nativelink-cas
          port: 50051
---
apiVersion: gateway.networking.k8s.io/v1alpha2
kind: GRPCRoute
metadata:
  name: scheduler-route
spec:
  parentRefs:
    - name: scheduler
      sectionName: scheduler
  rules:
    - backendRefs:
        - name: nativelink-scheduler
          port: 50052
